# Generated by Django 2.0.2 on 2018-04-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CFG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre de la grámatica Libre de Contexto', max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Ingrese alguna descripción acerca de la GLC.', verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='NonTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ingrese un valor para la terminal', max_length=150, verbose_name='Valor')),
                ('cfg', models.ForeignKey(help_text='Seleccion la GLC', on_delete=django.db.models.deletion.CASCADE, to='cfg.CFG', verbose_name='Gramática Libre de Contexto')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Ingrese la producción o producciones divididas por | en caso de que haya multiples por No Terminal. Si         se necesita un Epsilon entonces usar la palabra reservada EPSI', verbose_name='Valor')),
                ('cfg', models.ForeignKey(help_text='Seleccion la GLC', on_delete=django.db.models.deletion.CASCADE, to='cfg.CFG', verbose_name='Gramática Libre de Contexto')),
                ('non_terminal', models.ForeignKey(help_text='Seleccione un No Terminal para la producción.', on_delete=django.db.models.deletion.CASCADE, to='cfg.NonTerminal', verbose_name='No Terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ingrese un valor para la terminal', max_length=150, verbose_name='Valor')),
                ('cfg', models.ForeignKey(help_text='Seleccion la GLC', on_delete=django.db.models.deletion.CASCADE, to='cfg.CFG', verbose_name='Gramática Libre de Contexto')),
            ],
        ),
    ]
