# Generated by Django 2.0.2 on 2018-02-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre de la automata.', max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Brinde una breve explicación acerca de la automata', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Automata',
                'verbose_name_plural': 'Automatas',
            },
        ),
        migrations.CreateModel(
            name='AutomataLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ingrese el carácter aceptado por esta automata', max_length=1, verbose_name='Caracter')),
                ('automata', models.ForeignKey(help_text='Seleccione la automata asociada a este estado.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.Automata', verbose_name='Automata')),
            ],
            options={
                'verbose_name': 'Caracter Aceptado por Automata',
                'verbose_name_plural': 'Caracteres Aceptados por Automata',
            },
        ),
        migrations.CreateModel(
            name='AutomataState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ingrese la etiqueta del estado. Ej: q0', max_length=2, verbose_name='Etiqueta')),
                ('automata', models.ForeignKey(help_text='Seleccione la automata asociada a este estado.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.Automata', verbose_name='Automata')),
            ],
            options={
                'verbose_name': 'Estado de Automata',
                'verbose_name_plural': 'Estados de Automata',
            },
        ),
        migrations.CreateModel(
            name='AutomataTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Cargue el archivo json de prueba para la automata.', upload_to='documents/', verbose_name='Archivo de prueba')),
                ('automata', models.ForeignKey(help_text='Seleccione la automata asociada a este estado.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.Automata', verbose_name='Automata')),
            ],
            options={
                'verbose_name': 'Prueba de Automata',
                'verbose_name_plural': 'Pruebas de Automata',
            },
        ),
        migrations.CreateModel(
            name='AutomataTransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automata', models.ForeignKey(help_text='Seleccione la automata asociada a este estado.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.Automata', verbose_name='Automata')),
                ('transition_from', models.ForeignKey(help_text='Seleccione el estado donde comienza la transición.', on_delete=django.db.models.deletion.CASCADE, related_name='transition_from', to='automata_generator.AutomataState')),
                ('transition_to', models.ForeignKey(help_text='Seleccione el estado donde comienza la transición.', on_delete=django.db.models.deletion.CASCADE, related_name='transition_to', to='automata_generator.AutomataState')),
                ('value', models.ForeignKey(help_text='Seleccion el valor de la transición', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.AutomataLanguage')),
            ],
            options={
                'verbose_name': 'Transición de Automata',
                'verbose_name_plural': 'Transiciones de Automatas',
            },
        ),
    ]
