# Generated by Django 2.0.2 on 2018-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatastate',
            name='final_state',
            field=models.BooleanField(default=False, verbose_name='Es estado final?'),
        ),
        migrations.AddField(
            model_name='automatastate',
            name='start_state',
            field=models.BooleanField(default=True, verbose_name='Es estado inicio?'),
        ),
    ]
