# Generated by Django 2.0.2 on 2018-02-22 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automata_generator', '0002_auto_20180222_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automatatest',
            name='file',
        ),
    ]
