# Generated by Django 2.0.2 on 2018-03-12 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automata_generator', '0007_auto_20180312_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='automata',
            name='dfa_associated',
            field=models.ForeignKey(blank=True, help_text='Seleccione si tiene una sección padre, sino por favor deje el campo en blanco', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DFA', to='automata_generator.Automata'),
        ),
        migrations.AddField(
            model_name='automata',
            name='is_nfa',
            field=models.BooleanField(default=False, help_text='Seleccione si el automata es NFA', verbose_name='Es NFA?'),
        ),
        migrations.AddField(
            model_name='automata',
            name='is_nfa_eps',
            field=models.BooleanField(default=False, help_text='Seleccione si el automata es NFA', verbose_name='Es NFA EPS?'),
        ),
    ]
