# Generated by Django 2.0.2 on 2018-03-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata_generator', '0008_auto_20180312_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatastate',
            name='start_state',
            field=models.BooleanField(default=False, verbose_name='Es estado inicio?'),
        ),
    ]
