# Generated by Django 2.0.2 on 2018-04-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automata_generator', '0009_auto_20180312_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del PDA', max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(help_text='Descripción del PDA', verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='PDAState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Ingrese la etiqueta', max_length=2, verbose_name='Etiqueta')),
                ('start_state', models.BooleanField(default=False, verbose_name='Es estado inicio?')),
                ('final_state', models.BooleanField(default=False, verbose_name='Es estado final?')),
                ('pda', models.ForeignKey(help_text='Seleccione el PDA.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDA', verbose_name='PDA')),
            ],
        ),
        migrations.CreateModel(
            name='PDASymbolInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ingrese la etiqueta', max_length=2, verbose_name='Valor')),
                ('pda', models.ForeignKey(help_text='Seleccione el PDA.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDA', verbose_name='PDA')),
            ],
        ),
        migrations.CreateModel(
            name='PDASymbolStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ingrese la etiqueta', max_length=2, verbose_name='Valor')),
                ('start_symbol', models.BooleanField(default=False, verbose_name='Es símbolo incial?')),
                ('pda', models.ForeignKey(help_text='Seleccione el PDA.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDA', verbose_name='PDA')),
            ],
        ),
        migrations.CreateModel(
            name='PDATransition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransitionMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.TextField(verbose_name='Producción')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDAState', verbose_name='Estado')),
            ],
        ),
        migrations.AddField(
            model_name='pdatransition',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automata_generator.TransitionMove'),
        ),
        migrations.AddField(
            model_name='pdatransition',
            name='pda',
            field=models.ForeignKey(help_text='Seleccione el PDA.', on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDA', verbose_name='PDA'),
        ),
        migrations.AddField(
            model_name='pdatransition',
            name='pda_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDASymbolInput'),
        ),
        migrations.AddField(
            model_name='pdatransition',
            name='pda_stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDASymbolStack'),
        ),
        migrations.AddField(
            model_name='pdatransition',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automata_generator.PDAState', verbose_name='Estado'),
        ),
    ]
