# Generated by Django 2.0.2 on 2018-04-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automata_generator', '0011_auto_20180405_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdasymbolstack',
            name='value',
            field=models.CharField(help_text='Ingrese la etiqueta', max_length=255, verbose_name='Valor'),
        ),
    ]
